behaviors:
  Play2048:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 12800
      learning_rate: 0.00003
      beta: 0.000001
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 1000
    summary_freq: 5000
